// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLvU9Gy6AnCwJAAiQBHCbF-0yKRS8a4iY',
    appId: '1:171853474067:web:36053d674458e97eac52e6',
    messagingSenderId: '171853474067',
    projectId: 'my-quiz-app-92e44',
    authDomain: 'my-quiz-app-92e44.firebaseapp.com',
    storageBucket: 'my-quiz-app-92e44.appspot.com',
    measurementId: 'G-GHFHP8FSX8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYc5Opc1arhFgiwO2GzjfPdtQ6QeJWxIw',
    appId: '1:171853474067:android:336578073f80697aac52e6',
    messagingSenderId: '171853474067',
    projectId: 'my-quiz-app-92e44',
    storageBucket: 'my-quiz-app-92e44.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3vSGb5N7rgAIqvaxmvohC4JXejg4i694',
    appId: '1:171853474067:ios:6d42177fe0564707ac52e6',
    messagingSenderId: '171853474067',
    projectId: 'my-quiz-app-92e44',
    storageBucket: 'my-quiz-app-92e44.appspot.com',
    iosBundleId: 'com.example.quizApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3vSGb5N7rgAIqvaxmvohC4JXejg4i694',
    appId: '1:171853474067:ios:af23cee8983de45fac52e6',
    messagingSenderId: '171853474067',
    projectId: 'my-quiz-app-92e44',
    storageBucket: 'my-quiz-app-92e44.appspot.com',
    iosBundleId: 'com.example.quizApp.RunnerTests',
  );
}
